version: "3.0"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./nextcloud/appdata:/config
      - ./nextcloud/data:/data
    ports:
      - 4443:443
    restart: unless-stopped

  economy:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    ports:
      - 8080:8080
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=
      - DB_PORT=3306
      - DB_DATABASE=
      - DB_USERNAME=
      - DB_PASSWORD=
