version: "3.0"
services:
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - /docker/proxy/data:/data
      - /docker/proxy/letsencrypt:/etc/letsencrypt
      
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /docker/nextcloud/appdata:/config
      - /docker/nextcloud/data:/data
    ports:
      - 4443:443
    restart: unless-stopped

  economy:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    ports:
      - 8080:8080
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=
      - DB_PORT=3306
      - DB_DATABASE=
      - DB_USERNAME=
      - DB_PASSWORD=
