version: "3.0"
services:
  portainer:
    image: portainer/portainer-ce:2.11.1
    restart: always
    container_name: Portainer
    ports:
      - "9443:9443"

  pihole:
    image: pihole/pihole
    container_name: PiHole
    ports:
      - "8530:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" #DHCP
    environment:
      TZ: 'Europe/Madrid'
    volumes:
      - '/docker/etc/pihole:/etc/pihole'
      - '/docker/etc/dnsmasq.d:/etc/dnsmasq.d'
      - '/etc/resolv.conf:/etc/resolv.conf'
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - TZ=Europe/Madrid
    ports:
      - 8096:8096
    volumes:
      - /docker/config/jellyfin:/config
      - /docker/cache/jellyfin:/cache
      - /srv/2tb/Multimedia:/media
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /docker/config/transmission:/config
      - /srv/2tb/Torrent/Completados:/completados
      - /srv/2tb/Torrent/Pendientes:/pendientes
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
