version: "3.0"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - TZ=Europe/Madrid
    ports:
      - 8096:8096
    volumes:
      - /docker/config/jellyfin:/config
      - /docker/cache/jellyfin:/cache
      - /srv/2tb/Multimedia:/media
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /docker/config/transmission:/config
      - /srv/2tb/Torrent/Completados:/downloads/complete
      - /srv/2tb/Torrent/Pendientes:/downloads/incomplete
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /docker/homeassistant/config:/config
    ports:
      - 8123:8123 #optional
    restart: unless-stopped
  
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - /docker/proxy/data:/data
      - /docker/proxy/letsencrypt:/etc/letsencrypt
  
  deemix:
    image: finniedj/deemix
    container_name: deemix
    volumes:
      - /srv/2tb/Multimedia/Musica:/downloads
      - /docker/deemix/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
    ports:
      - 6595:6595

  metube:
    image: alexta69/metube
    container_name: metube
    ports:
      - "8081:8081"
    volumes:
      - /srv/2tb/Multimedia/YT-dl:/downloads
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - /docker/vw/data:/data
    ports:
      - 80:80
